name: Label issues that need first responding
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  first-responder-label:

    runs-on: ubuntu-latest

    steps:
    - name: Label new issues with needs-fr
      uses: rachmari/labeler@v1.0.3
      if: ( !contains(github.event.issue.labels.*.name, 'project-triaged'))
      with:
        repo-token: "${{ secrets.REPO_ALL_ORG_READ }}"
        add-labels: "needs-fr"
        team: "rachmari-sprokets-inc/teamjacob"
