name: Check unallowed file changes

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request number
        id: pull-number
        uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            if (context.eventName == 'pull_request') {
              console.log(context.payload.number)
            } else {
              console.log('Push event')
            }
