name: Triage issue to project board

on:
  issues:
    types: [labeled]
    
jobs:
  triage-issue-to-project-board:
    runs-on: ubuntu-latest
    steps:    
      - name: Add needs-triage label  
        uses: andymckay/labeler@1.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          remove-labels: "needs-fr"
