name: Triage issue to project board

on:
  issues:
    types: [labeled]
    
jobs:
  triage-issue-to-project-board:
    runs-on: ubuntu-latest
    steps:    
      - name: Add needs-triage label  
        uses: rachmari/labeler@rachmari-fix-remove-only-bug
        if: contains(github.event.issue.labels.*.name, 'core')
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          remove-labels: "needs-fr"
